In [20]:
import numpy as np

a = np.ones((3,3))
print(a)
b = np.zeros((3,3))
print(b)

da = np.gradient(a)
print(da)

ab = np.concatenate([a, b])
ab = np.concatenate([ab, ab], 1)
print(ab)

print('---')
dab = np.gradient(ab, axis=0)
print(dab)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
---
[[ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]]


In [34]:
import torch

a = np.ones((3,3))
b = np.zeros((3,3))

da = np.gradient(a)

ab = np.concatenate([a, b])
ab = np.concatenate([ab, ab], 1)

ab = torch.from_numpy(ab)
ab = torch.autograd.Variable(ab, requires_grad=True)
print(ab)
print(ab.grad)

w = torch.mean(ab)
print(w)
w.backward()
print(ab.grad)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)
None
tensor(0.5000, dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor([[0.0278, 0.0278, 0.0278, 0.0278, 0.0278, 0.0278],
        [0.0278, 0.0278, 0.0278, 0.0278, 0.0278, 0.0278],
        [0.0278, 0.0278, 0.0278, 0.0278, 0.0278, 0.0278],
        [0.0278, 0.0278, 0.0278, 0.0278, 0.0278, 0.0278],
        [0.0278, 0.0278, 0.0278, 0.0278, 0.0278, 0.0278],
        [0.0278, 0.0278, 0.0278, 0.0278, 0.0278, 0.0278]], dtype=torch.float64)


In [39]:
import torch

a = torch.autograd.Variable(torch.Tensor([1, 2, 3]), requires_grad=True)
print(a)
w = torch.mean(a)
print(w)
w.backward()
print(a.grad)

tensor([1., 2., 3.], requires_grad=True)
tensor(2., grad_fn=<MeanBackward0>)
tensor([0.3333, 0.3333, 0.3333])


### Simple Gradient

In [48]:
import torch as T
from torch.autograd import Variable as V

a = V(T.FloatTensor([2, 3]), requires_grad=True)
print(a)

b = a + 3
print(b)

c = b**2 + 2
print(c)

out = c.mean()
print(out)

out.backward()

print(a.grad)

tensor([2., 3.], requires_grad=True)
tensor([5., 6.], grad_fn=<AddBackward0>)
tensor([27., 38.], grad_fn=<AddBackward0>)
tensor(32.5000, grad_fn=<MeanBackward0>)
tensor([5., 6.])


In [52]:
import torch as T
from torch.autograd import Variable as V


x = V(T.ones(2, 2), requires_grad=True)
y = x + 1

sy = T.sum(y)

print(sy)
sy.backward()

print(x.grad)
print(y.grad)
print(sy.grad)

tensor(8., grad_fn=<SumBackward0>)
tensor([[1., 1.],
        [1., 1.]])
None
None


In [62]:
import torch as T
from torch.autograd import Variable as V

grad_list = []

def print_grad(grad):
    print(grad)
    grad_list.append(grad)


a = V(T.FloatTensor([2.0]), requires_grad=True)
a.register_hook(print_grad)

b = a**2 + 1
b.register_hook(print_grad)

c = b + 1
c.register_hook(print_grad)

c.backward()

print('--')
print(b.grad)
print(a.grad)

print('--')
for grad in grad_list:
    print(grad)

tensor([1.])
tensor([1.])
tensor([4.])
--
None
tensor([4.])
--
tensor([1.])
tensor([1.])
tensor([4.])
